### ISSUE TITLE
Identify command run when book loaded

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#117]
Is this needed? It should be avoided if possible.

**Comment by jabrah** [comment]
This looks like a leftover from the older Rosa1 code that was used to get things rolling when first implementing the book loading. 

[rosa.archive.core.StoreImpl#getImageDimensionsHack(String)](https://github.com/jhu-digital-manuscripts/rosa2/blob/master/rosa-archive/rosa-archive-core/src/main/java/rosa/archive/core/StoreImpl.java#L1222)

When loading a collection, it seems that this is used to read the dimensions of the "missing image" in order to set correct dimensions on placeholders of any pages that are missing.

Replace this with something simpler, perhaps just some entries in a properties file?

**Comment by markpatton** [comment]
I was worried it was being done on every image! We should replace this with a java library or just add it to the collection config.properties.
